name: strchive

channels:
  - bioconda
  - conda-forge

dependencies:
  - pandas
  - numpy
  - biopython
  - defopt
  - snakemake
  - jsbeautifier
  - jsonschema
  - r-essentials
  - r-jsonlite
  - r-dplyr
  - r-rentrez
  - r-easypubmed
  - r-stringr
  - r-purrr
  - pip
  - pip:
    - manubot
